name: Iran Radar Update

on:
  schedule:
    - cron: '*/45 * * * *' # Runs every 45 minutes
  workflow_dispatch:      # Allows manual run
    inputs:
      manual_url:
        description: 'Paste a specific News URL to process (Leave empty for normal mode)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run News Script
        env: 
          POLLINATIONS_API_KEY: ${{ secrets.POLLINATIONS_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
          # Pass the manual input to an Environment Variable
          MANUAL_URL: ${{ inputs.manual_url }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "IranRadarBot"
          git config --global user.email "bot@noreply.github.com"
          
          git add news.json market.json
          
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news feed" && git push)
